### ISSUE TITLE
When to set use_multi_fc over and bias flags?

### ISSUE THREAD

**Issue by Akella17** [arthurdouillard/incremental_learning.pytorch#10]
Can you mention the reason behind the use of multi_fc (E2E) and single_fc (iCaRL and LwF)? Also, when does one set the bias in the classifier (True for E2E and iCaRL while False for LwF)?

**Comment by arthurdouillard** [comment]
1. I've tried multi_fc and single_fc. They should have comparable results. I've used multi_fc because I thought it was how authors implemented it (although I can't read matlab...). Use single_fc by default.

2. Kinda same answer for bias. Use it if it improves your model performance, else don't.
