### ISSUE TITLE
Excuse me, how do I run your code, such as run icarl.

### ISSUE THREAD

**Issue by ChengtaiCao** [arthurdouillard/incremental_learning.pytorch#12]
Excuse me, how do I run your code, such as run icarl.

**Comment by arthurdouillard** [comment]
With several default params:

```
python3 -minclearn --model icarl --increment 10
```

**Comment by JoyHuYY1412** [comment]
Sorry, how about running LwM? What's more, how to change the class order since I just want from 1~100. Thanks so much.

**Comment by JoyHuYY1412** [comment]
> With several default params:
> 
> ```
> python3 -minclearn --model icarl --increment 10
> ```
Sorry, how about running LwM? What's more, how to change the class order since I just want from 1~100. Thanks so much.
