### ISSUE TITLE
Status of some of the models

### ISSUE THREAD

**Issue by gunshi** [arthurdouillard/incremental_learning.pytorch#14]
Hi @arthurdouillard ,
thanks for the great readable code!
I had a question about whether some of the implemented models like 'medic' are complete in the sense of reproducing the paper's results?
Asking because the readme doesn't mention their status.
Thanks again,
Gunshi

**Comment by arthurdouillard** [comment]
Hello,
This repo is not yet up to date with my local code. I've however have not make MEDIC work.
Feel free to start from my draft if you want :)

**Comment by gunshi** [comment]
Got it, thanks!
