### ISSUE TITLE
Can anyone get the result of LwM?

### ISSUE THREAD

**Issue by JoyHuYY1412** [arthurdouillard/incremental_learning.pytorch#19]
I run 
`python -minclearn --model lwm --increment 20 -memory 0`. And I change `self._attention_config = args.get("attention_config", {"factor":1})` and `self._distillation_config["factor"] =1` in lwm.py.

However, the result is very low. Could anyone give me some advice?

**Comment by arthurdouillard** [comment]
I've never been able to reach the results of LwM. And to be honest I have some doubt about the papers results, as they seem very high while using no rehearsal memory.
