### ISSUE TITLE
about  the podLoss

### ISSUE THREAD

**Issue by liujianzhao6328057** [arthurdouillard/incremental_learning.pytorch#26]
Hi,thanks for your great work.  I wonder why " a = torch.pow(a, 2) b = torch.pow(b, 2)"  in advance ? Thank you.
(https://github.com/arthurdouillard/incremental_learning.pytorch/blob/889359036fea30aa5f8dd2b69455bce507dd601c/inclearn/lib/losses/distillation.py#L64)

**Comment by arthurdouillard** [comment]
Hey,

Squaring the features before doing the POD embedding improves results. This trick has been seen multiple time in features-based distillation, see this paper https://arxiv.org/abs/1612.03928 for more information about it.

Note that the squaring is better for POD, but also for alternative (POD-pixels, POD-channels, etc.).
