### ISSUE TITLE
Would you share the python version?

### ISSUE THREAD

**Issue by liuyu19970607** [arthurdouillard/incremental_learning.pytorch#28]
Something wrong when running the code:
"?it/spython3: symbol lookup error: /home/anaconda3/envs/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack"

could you share the python version? Thanks for your time~

**Comment by arthurdouillard** [comment]
I've used 3.6 and 3.7 for python version.

Pytorch version, as mentioned in the requirements.txt, is 1.2.0 but later versions should also work.

Hope that helps!
