### ISSUE TITLE
Python and PyTorch version

### ISSUE THREAD

**Issue by luhaochun** [arthurdouillard/incremental_learning.pytorch#29]
Hi, I was wondering if you could provide the Python and PyTorch versions that this code was tested with?

**Comment by arthurdouillard** [comment]
Python is 3.6, Pytorch is 1.2.0.

Please look at the requirements: https://github.com/arthurdouillard/incremental_learning.pytorch/blob/master/requirements.txt#L1

Anyway, the code should work for later version of Pytorch.

**Comment by arthurdouillard** [comment]
If testing PODNet NME (PODNet CNN should be fine) or BiC, try first with torch version 1.2.0 (https://github.com/arthurdouillard/incremental_learning.pytorch/issues/31). I'm not sure yet why.
