### ISSUE TITLE
Configurations related to reproduce lwm

### ISSUE THREAD

**Issue by Kingofolk** [arthurdouillard/incremental_learning.pytorch#39]
hello!
thank you for your great work! Recently I want to use your code to reproduce lwm but I didn't find the option file. Could you please  share me the configurations related to lwm? A lot of thanks!

best wishes!

**Comment by arthurdouillard** [comment]
Thanks for the kind words.

I've pushed a draft of an option file for LwM: https://github.com/arthurdouillard/incremental_learning.pytorch/blob/master/options/lwm/lwm_cifar100.yaml

However, please note that I haven't been able to reproduce the paper results. If you find a way, please tell me!

Best,
