### ISSUE TITLE
About UCIR configuration

### ISSUE THREAD

**Issue by BinahHu** [arthurdouillard/incremental_learning.pytorch#42]
Thank you so much for this excellent work!

I am a little confusing about the epoch number for ucir in the latest version (ucir_cifar100.yaml, line 42). It seems that you change it from 160 to 1. However, in the  [original implementation of UCIR](https://github.com/hshustc/CVPR19_Incremental_Learning/blob/e5a90aed7640f3b00e5b1a8dfb5376c1628bfe6a/cifar100-class-incremental/class_incremental_cosine_cifar100.py#L50), such number is 160. Moreover, I tried to reproduce UCIR using  the current configuration, the results are awful (15.17% average acc).

I am wondering if this is a typo, or you have a higher level of consideration? Thank you so much!

**Comment by arthurdouillard** [comment]
Thanks for the kind words :)

I was just testing the model when I used 1 epoch, the correct number is obviously 160 as you well remarked.
Unfortunatly, even with 160 epochs my results were a little under those of the original paper if I recall.

**Comment by BinahHu** [comment]
Thank you for your reply!

It's fine if the reproduced performance is a bit lower. That's acceptable!
