### ISSUE TITLE
Finetune in PODNet

### ISSUE THREAD

**Issue by KHao123** [arthurdouillard/incremental_learning.pytorch#48]
The code conduct finetune stage in training phase. It seem not be mentioned in the paper.  Is the result reported in paper obtained with finetune?

**Comment by arthurdouillard** [comment]
Hello,

Yes we do the same finetuning as UCIR. In the paper, it is only done for the CNN model but not for the NME model.
You can check the provided options files in this github that were used to produce the paper.
