### ISSUE TITLE
ImageNet 100 label index. Why choose these label index

### ISSUE THREAD

**Issue by qsunyuan** [arthurdouillard/incremental_learning.pytorch#52]
https://github.com/HobbitLong/CMC/issues/21
https://www.kaggle.com/ambityga/imagenet100

I found there are different versions of ImageNet 100. 

So, I was so confused which one should I choose.

Is it a simple random selection of labels?

Hope to get ur replay early.

Thx.

**Comment by arthurdouillard** [comment]
I've just chosen it randomly since I didn't see one official version of imagenet100.

Although, all models in my PODNet papers used the same class ids; and following works, such as DER (cvpr2021) also uses my subset.
