### ISSUE TITLE
 How can i change dataset?

### ISSUE THREAD

**Issue by semihenser** [arthurdouillard/incremental_learning.pytorch#55]
I need to change the dataset. I pasted this code in anaconda prompt.
![image](https://user-images.githubusercontent.com/51171376/149218357-e47343e7-a261-41e2-b0ac-100a2c075b6a.png)

After doing this I got these errors.How can i solve this?
![image](https://user-images.githubusercontent.com/51171376/149219077-771bc2e8-6097-44a4-aed6-ed7f52579c48.png)

Is there an easier way to change the dataset?

**Comment by arthurdouillard** [comment]
Hello,

You need to change the path in the options file: https://github.com/arthurdouillard/incremental_learning.pytorch/blob/master/options/data/imagenet100_1order.yaml#L2

As you can see the path was for my computer, you need to provide the path to ImageNet on your computer.
