### ISSUE TITLE
The scaling prarameter in the classifier

### ISSUE THREAD

**Issue by windbro98** [arthurdouillard/incremental_learning.pytorch#66]
Excuse me, sir. When I'm reading your paper, I feel amazed that there is a learnable parameter, $\eta$, in the classifer. 

However, when I look into the codes, I find that the only possible variable corresponding to the $\eta$ is the **self.scaling**. It is set to be an integer 1 in default, which means that it's not learnable.

I'd like to know that, this is set by purpose, or just a mistask?

**Comment by arthurdouillard** [comment]
PODNet uses `FactorScalar` (https://github.com/arthurdouillard/incremental_learning.pytorch/blob/0d25c2e12bde4a4a25f81d5e316751c90e6f789b/inclearn/lib/network/postprocessors.py#L26) which is a learned scalar. While initialzied at one, it's still learned.

It helps the optimization with cosine classifier.

**Comment by windbro98** [comment]
Thank you, sir. Your answer really helps me a lot.
