### ISSUE TITLE
E2E code is not using exemplars

### ISSUE THREAD

**Issue by Akella17** [arthurdouillard/incremental_learning.pytorch#9]
Where is the train loader being appended with old class exemplars in E2E model. For instance, before doing [this](https://github.com/arthurdouillard/incremental_learning.pytorch/blob/5bba3d3d064054f62a8deac8cb9aa0b131afd756/inclearn/models/e2e.py#L97), shouldn't we be updating the train loader by adding the old-class exemplars aswell?

**Comment by arthurdouillard** [comment]
My online code is not up to date, especially for E2E but yes it was using the examplars.

See iCaRL to adapt E2E to use my new way of handling examplars.
